[package]
name = "local-watcher"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
mongodb = { version = "2.6", features = ["tokio-sync"] }
futures = "0.3"
serde_json = "1.0.145"